// generated by rpg2java-transpiler (target=java21)
public class As400HybridStyle {
    public static void main(String[] args) {
        double CNT = 0;
        boolean IN90 = false;
        Object KEY;
        Object LOGERR;
        Object MASTER;
        Object file;
        Object key;
        Object subroutine;

        // TODO(CHAIN): key=KEY, file=MASTER
        if (truthy(IN90)) {
            // TODO(EXSR): subroutine=LOGERR
        } else {
            CNT = CNT + 1;
        }
    }

    private static void writeRecord(Object rec) {
        // TODO: replace with repository/output adapter
    }

    private static void readRecord(Object rec) {
        // TODO: replace with repository/input adapter
    }

    private static boolean truthy(Object v) {
        if (v == null) return false;
        if (v instanceof Boolean) return (Boolean) v;
        if (v instanceof Number) return ((Number) v).doubleValue() != 0.0;
        return !v.toString().isBlank();
    }
}
