// generated by rpg2java-transpiler (target=java21)
public class Rpg3FixedCalc {
    public static void main(String[] args) {
        Object LIMIT;
        Object ORDER_REC;
        double PRICE = 0;
        double TAX = 0;
        double TOTAL = 0;

        TOTAL = PRICE + TAX;
        if (truthy(LIMIT)) {
            writeRecord(ORDER_REC);
        }
    }

    private static void writeRecord(Object rec) {
        // TODO: replace with repository/output adapter
    }

    private static void readRecord(Object rec) {
        // TODO: replace with repository/input adapter
    }

    private static boolean truthy(Object v) {
        if (v == null) return false;
        if (v instanceof Boolean) return (Boolean) v;
        if (v instanceof Number) return ((Number) v).doubleValue() != 0.0;
        return !v.toString().isBlank();
    }
}
