use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn make_temp_dir(name: &str) -> PathBuf {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock error")
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("rpg2java-{name}-{}-{ts}", std::process::id()));
    fs::create_dir_all(&dir).expect("failed to create temp dir");
    dir
}

fn normalize_java_body(java: &str) -> String {
    let mut out = String::new();
    for line in java.lines() {
        if line.starts_with("// generated by rpg2java-transpiler") {
            continue;
        }
        if line.starts_with("// profile: ") {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

#[test]
fn java21_and_java25_stable_have_same_core_output() {
    let base = make_temp_dir("java-target-policy");
    let input = base.join("sample.rpg");
    let java21 = base.join("Sample21.java");
    let java25 = base.join("Sample25.java");

    fs::write(
        &input,
        "EVAL class = 1\nCALLP switch\nIF class *GT 0\nWRITE rec\nENDIF\n",
    )
    .expect("failed to write fixture");

    let bin = env!("CARGO_BIN_EXE_rpg2java-transpiler");
    let out21 = Command::new(bin)
        .arg("--input")
        .arg(&input)
        .arg("--output")
        .arg(&java21)
        .arg("--class-name")
        .arg("class")
        .arg("--java-target")
        .arg("java21")
        .arg("--mode")
        .arg("free")
        .output()
        .expect("failed to execute binary");
    assert!(
        out21.status.success(),
        "java21 conversion failed\nstderr:\n{}",
        String::from_utf8_lossy(&out21.stderr)
    );

    let out25 = Command::new(bin)
        .arg("--input")
        .arg(&input)
        .arg("--output")
        .arg(&java25)
        .arg("--class-name")
        .arg("class")
        .arg("--java-target")
        .arg("java25-stable")
        .arg("--mode")
        .arg("free")
        .output()
        .expect("failed to execute binary");
    assert!(
        out25.status.success(),
        "java25 conversion failed\nstderr:\n{}",
        String::from_utf8_lossy(&out25.stderr)
    );

    let body21 = fs::read_to_string(&java21).expect("failed to read java21 output");
    let body25 = fs::read_to_string(&java25).expect("failed to read java25 output");

    assert!(body21.contains("target=java21"), "java21={body21}");
    assert!(body25.contains("target=java25-stable"), "java25={body25}");
    assert!(body25.contains("// profile: java25 stable language/runtime surface"));
    assert!(
        !body21.contains("// profile: java25 stable language/runtime surface"),
        "java21={body21}"
    );

    let normalized21 = normalize_java_body(&body21);
    let normalized25 = normalize_java_body(&body25);
    assert_eq!(
        normalized21, normalized25,
        "core generated Java must be identical between java21 and java25-stable"
    );
}
