use std::collections::{BTreeMap, BTreeSet};

use crate::ir::{IrProgram, IrStmt, ValueType};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JavaTarget {
    Java21,
    Java25Stable,
}

impl JavaTarget {
    pub fn as_str(self) -> &'static str {
        match self {
            JavaTarget::Java21 => "java21",
            JavaTarget::Java25Stable => "java25-stable",
        }
    }
}

pub fn parse_java_target(value: &str) -> Result<JavaTarget, String> {
    match value.to_ascii_lowercase().as_str() {
        "java21" => Ok(JavaTarget::Java21),
        "java25-stable" => Ok(JavaTarget::Java25Stable),
        _ => Err(format!(
            "invalid --java-target '{}', expected java21|java25-stable",
            value
        )),
    }
}

pub fn to_java(program: &IrProgram, class_name: &str, target: JavaTarget) -> String {
    let mut out = String::new();
    let class_name = sanitize_ident(class_name);
    let name_map = build_name_map(program, &class_name);
    let proc_map = build_proc_name_map(program, &name_map, &class_name);
    let mut type_map: BTreeMap<String, ValueType> = BTreeMap::new();
    for symbol in &program.symbols {
        type_map.insert(symbol.name.clone(), symbol.ty);
        type_map
            .entry(symbol.name.to_ascii_uppercase())
            .or_insert(symbol.ty);
    }

    out.push_str(&format!(
        "// generated by rpg2java-transpiler (target={})\n",
        target.as_str()
    ));
    if target == JavaTarget::Java25Stable {
        out.push_str("// profile: java25 stable language/runtime surface\n");
    }
    out.push_str("public class ");
    out.push_str(&class_name);
    out.push_str(" {\n");
    out.push_str("    public static void main(String[] args) {\n");

    for symbol in &program.symbols {
        let java_name = map_ident(&symbol.name, &name_map);
        let ty = match symbol.ty {
            ValueType::Number => "double",
            ValueType::Text => "String",
            ValueType::Bool => "boolean",
            ValueType::Unknown => "Object",
        };
        let init = match symbol.ty {
            ValueType::Number => " = 0;",
            ValueType::Text => " = \"\";",
            ValueType::Bool => " = false;",
            ValueType::Unknown => ";",
        };
        push_line(&mut out, 2, &format!("{ty} {java_name}{init}"));
    }
    if !program.symbols.is_empty() {
        out.push('\n');
    }

    let mut called_methods: BTreeSet<String> = BTreeSet::new();
    let mut indent = 2usize;
    for stmt in &program.statements {
        match stmt {
            IrStmt::Assign { left, right } => {
                let left_name = map_ident(left, &name_map);
                let left_ty = type_map.get(left).copied().unwrap_or(ValueType::Unknown);
                let rendered = render_assignment_expr(right, &name_map, &type_map, left_ty);
                if let Some(reason) = rendered.fallback_reason {
                    push_line(
                        &mut out,
                        indent,
                        &format!("// TODO(FALLBACK_EXPR): {right} ({reason})"),
                    );
                }
                push_line(&mut out, indent, &format!("{left_name} = {};", rendered.java_expr));
            }
            IrStmt::If { cond } => {
                let rendered = render_condition_expr(cond, &name_map, &type_map, false);
                if let Some(reason) = rendered.fallback_reason {
                    push_line(
                        &mut out,
                        indent,
                        &format!("// TODO(FALLBACK_COND): {cond} ({reason})"),
                    );
                }
                push_line(&mut out, indent, &format!("if ({}) {{", rendered.java_expr));
                indent += 1;
            }
            IrStmt::Else => {
                indent = indent.saturating_sub(1);
                push_line(&mut out, indent, "} else {");
                indent += 1;
            }
            IrStmt::EndIf => {
                indent = indent.saturating_sub(1);
                push_line(&mut out, indent, "}");
            }
            IrStmt::DoUntil { cond } => {
                let rendered = render_condition_expr(cond, &name_map, &type_map, true);
                if let Some(reason) = rendered.fallback_reason {
                    push_line(
                        &mut out,
                        indent,
                        &format!("// TODO(FALLBACK_COND): {cond} ({reason})"),
                    );
                }
                push_line(&mut out, indent, &format!("while (!({})) {{", rendered.java_expr));
                indent += 1;
            }
            IrStmt::EndDo => {
                indent = indent.saturating_sub(1);
                push_line(&mut out, indent, "}");
            }
            IrStmt::Call { proc_name } => {
                let proc = map_ident(proc_name, &proc_map);
                called_methods.insert(proc.clone());
                push_line(&mut out, indent, &format!("{proc}();"));
            }
            IrStmt::Write { target } => {
                let target = map_ident(target, &name_map);
                push_line(&mut out, indent, &format!("writeRecord({target});"));
            }
            IrStmt::Read { target } => {
                let target = map_ident(target, &name_map);
                push_line(&mut out, indent, &format!("readRecord({target});"));
            }
            IrStmt::Todo { op, src } => {
                if let Some(op) = op {
                    push_line(&mut out, indent, &format!("// TODO({op}): {src}"));
                } else {
                    push_line(&mut out, indent, &format!("// TODO: {src}"));
                }
            }
        }
    }

    while indent > 2 {
        indent -= 1;
        push_line(&mut out, indent, "}");
    }

    out.push_str("    }\n");
    out.push_str("\n");
    for proc in called_methods {
        out.push_str("    private static void ");
        out.push_str(&proc);
        out.push_str("() {\n");
        out.push_str("        // TODO: migrated from CALLP\n");
        out.push_str("    }\n\n");
    }
    out.push_str("    private static void writeRecord(Object rec) {\n");
    out.push_str("        // TODO: replace with repository/output adapter\n");
    out.push_str("    }\n");
    out.push_str("\n");
    out.push_str("    private static void readRecord(Object rec) {\n");
    out.push_str("        // TODO: replace with repository/input adapter\n");
    out.push_str("    }\n");
    out.push_str("\n");
    out.push_str("    private static boolean truthy(Object v) {\n");
    out.push_str("        if (v == null) return false;\n");
    out.push_str("        if (v instanceof Boolean) return (Boolean) v;\n");
    out.push_str("        if (v instanceof Number) return ((Number) v).doubleValue() != 0.0;\n");
    out.push_str("        return !v.toString().isBlank();\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn push_line(buf: &mut String, indent: usize, line: &str) {
    buf.push_str(&"    ".repeat(indent));
    buf.push_str(line);
    buf.push('\n');
}

fn normalize_cond(cond: &str) -> String {
    normalize_rpg_expr_tokens(cond)
}

fn translate_cond(
    cond: &str,
    name_map: &BTreeMap<String, String>,
    type_map: &BTreeMap<String, ValueType>,
) -> String {
    if let Some(single) = translate_single_indicator_cond(cond, name_map) {
        return single;
    }

    let c = normalize_cond(cond);
    let c = replace_fixed_indicator_refs(&c);
    if contains_comparator(&c) {
        return translate_expr(&c, name_map, type_map, true);
    }
    if contains_logical_operator(&c) {
        return translate_expr(&c, name_map, type_map, false);
    }
    let expr = translate_expr(&c, name_map, type_map, false);
    format!("truthy({expr})")
}

fn translate_single_indicator_cond(
    cond: &str,
    name_map: &BTreeMap<String, String>,
) -> Option<String> {
    let upper = cond.trim().to_ascii_uppercase();
    if upper.is_empty() {
        return None;
    }

    if let Some(ind) = parse_positive_indicator_cond_token(&upper) {
        let mapped = map_ident(&format!("IN{ind}"), name_map);
        return Some(format!("truthy({mapped})"));
    }
    if let Some(ind) = parse_negative_indicator_cond_token(&upper) {
        let mapped = map_ident(&format!("IN{ind}"), name_map);
        return Some(format!("!truthy({mapped})"));
    }
    None
}

struct RenderedExpr {
    java_expr: String,
    fallback_reason: Option<String>,
}

fn render_assignment_expr(
    expr: &str,
    name_map: &BTreeMap<String, String>,
    type_map: &BTreeMap<String, ValueType>,
    left_ty: ValueType,
) -> RenderedExpr {
    let unsupported = detect_unsupported_rpg_tokens(expr);
    if unsupported.is_empty() {
        return RenderedExpr {
            java_expr: translate_expr(expr, name_map, type_map, left_ty == ValueType::Number),
            fallback_reason: None,
        };
    }
    RenderedExpr {
        java_expr: fallback_literal_for_type(left_ty).to_string(),
        fallback_reason: Some(format!(
            "unsupported RPG token(s): {}",
            unsupported.join(", ")
        )),
    }
}

fn render_condition_expr(
    cond: &str,
    name_map: &BTreeMap<String, String>,
    type_map: &BTreeMap<String, ValueType>,
    is_dou: bool,
) -> RenderedExpr {
    let unsupported = detect_unsupported_rpg_tokens(cond);
    if unsupported.is_empty() {
        return RenderedExpr {
            java_expr: translate_cond(cond, name_map, type_map),
            fallback_reason: None,
        };
    }
    RenderedExpr {
        // DOU fallback to true so generated while(!(true)) does not spin forever.
        java_expr: if is_dou { "true" } else { "false" }.to_string(),
        fallback_reason: Some(format!(
            "unsupported RPG token(s): {}",
            unsupported.join(", ")
        )),
    }
}

fn fallback_literal_for_type(ty: ValueType) -> &'static str {
    match ty {
        ValueType::Number => "0",
        ValueType::Text => "\"\"",
        ValueType::Bool => "false",
        ValueType::Unknown => "null",
    }
}

fn detect_unsupported_rpg_tokens(expr: &str) -> Vec<String> {
    let mut out: BTreeSet<String> = BTreeSet::new();
    let chars: Vec<char> = expr.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        if chars[i] == '\'' || chars[i] == '"' {
            let quote = chars[i];
            i += 1;
            while i < chars.len() && chars[i] != quote {
                i += 1;
            }
            if i < chars.len() {
                i += 1;
            }
            continue;
        }

        if chars[i] == '*' {
            let start = i;
            i += 1;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let tok: String = chars[start..i].iter().collect();
            let upper = tok.to_ascii_uppercase();
            if is_supported_star_token(&upper) {
                continue;
            }
            out.insert(tok);
            continue;
        }
        i += 1;
    }
    out.into_iter().collect()
}

fn is_supported_star_token(token_upper: &str) -> bool {
    if token_upper.starts_with("*IN")
        && token_upper.len() > 3
        && token_upper[3..].chars().all(|c| c.is_ascii_digit())
    {
        return true;
    }
    matches!(
        token_upper,
        "*EQ"
            | "*NE"
            | "*GT"
            | "*LT"
            | "*GE"
            | "*LE"
            | "*AND"
            | "*OR"
            | "*NOT"
            | "*ON"
            | "*OFF"
            | "*CAT"
    )
}

fn parse_positive_indicator_cond_token(token: &str) -> Option<String> {
    if token.len() == 2 && token.chars().all(|c| c.is_ascii_digit()) {
        return Some(token.to_string());
    }
    if token.len() == 4 && token.starts_with("IN") && token[2..].chars().all(|c| c.is_ascii_digit())
    {
        return Some(token[2..].to_string());
    }
    if token.len() == 5
        && token.starts_with("*IN")
        && token[3..].chars().all(|c| c.is_ascii_digit())
    {
        return Some(token[3..].to_string());
    }
    None
}

fn parse_negative_indicator_cond_token(token: &str) -> Option<String> {
    if token.len() == 3 && token.starts_with('N') && token[1..].chars().all(|c| c.is_ascii_digit())
    {
        return Some(token[1..].to_string());
    }
    let rest = token.strip_prefix("NOT ")?;
    parse_positive_indicator_cond_token(rest)
}

fn replace_fixed_indicator_refs(cond: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = cond.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        if chars[i] == '*' && i + 4 < chars.len() && chars[i + 1] == 'I' && chars[i + 2] == 'N' {
            let d1 = chars[i + 3];
            let d2 = chars[i + 4];
            if d1.is_ascii_digit() && d2.is_ascii_digit() {
                out.push_str("IN");
                out.push(d1);
                out.push(d2);
                i += 5;
                continue;
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

fn translate_expr(
    expr: &str,
    name_map: &BTreeMap<String, String>,
    type_map: &BTreeMap<String, ValueType>,
    numeric_context: bool,
) -> String {
    let normalized_expr = normalize_rpg_expr_tokens(expr);
    let mut out = String::new();
    let chars: Vec<char> = normalized_expr.chars().collect();
    let mut i = 0usize;

    while i < chars.len() {
        let ch = chars[i];
        if ch == '\'' || ch == '"' {
            let quote = ch;
            i += 1;
            let start = i;
            while i < chars.len() && chars[i] != quote {
                i += 1;
            }
            if i < chars.len() {
                let raw_content: String = chars[start..i].iter().collect();
                out.push_str(&to_java_string_literal(&raw_content));
                i += 1;
                continue;
            }
            out.push(quote);
            continue;
        }
        if ch.is_ascii_alphabetic() || ch == '_' {
            let start = i;
            i += 1;
            while i < chars.len() && (chars[i].is_ascii_alphanumeric() || chars[i] == '_') {
                i += 1;
            }
            let raw: String = chars[start..i].iter().collect();
            if raw.eq_ignore_ascii_case("true") || raw.eq_ignore_ascii_case("false") {
                out.push_str(&raw.to_ascii_lowercase());
                continue;
            }
            let mapped = map_ident(&raw, name_map);
            if numeric_context {
                let ty = type_map.get(&raw).copied().unwrap_or(ValueType::Unknown);
                match ty {
                    ValueType::Number => out.push_str(&mapped),
                    ValueType::Unknown => {
                        out.push_str("((Number)");
                        out.push_str(&mapped);
                        out.push_str(").doubleValue()");
                    }
                    ValueType::Text | ValueType::Bool => out.push_str(&mapped),
                }
            } else {
                out.push_str(&mapped);
            }
            continue;
        }
        out.push(ch);
        i += 1;
    }
    out
}

fn normalize_rpg_expr_tokens(expr: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = expr.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        let ch = chars[i];
        if ch == '\'' || ch == '"' {
            out.push(ch);
            i += 1;
            while i < chars.len() {
                let c = chars[i];
                out.push(c);
                i += 1;
                if c == ch {
                    break;
                }
            }
            continue;
        }
        if ch.is_ascii_whitespace() {
            out.push(ch);
            i += 1;
            continue;
        }
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '*' {
            let start = i;
            i += 1;
            while i < chars.len()
                && (chars[i].is_ascii_alphanumeric() || chars[i] == '_' || chars[i] == '*')
            {
                i += 1;
            }
            let token: String = chars[start..i].iter().collect();
            out.push_str(&normalize_rpg_token(&token));
            continue;
        }
        out.push(ch);
        i += 1;
    }
    out
}

fn normalize_rpg_token(token: &str) -> String {
    let upper = token.to_ascii_uppercase();
    match upper.as_str() {
        "*EQ" | "EQ" => String::from("=="),
        "*NE" | "NE" => String::from("!="),
        "*GT" | "GT" => String::from(">"),
        "*LT" | "LT" => String::from("<"),
        "*GE" | "GE" => String::from(">="),
        "*LE" | "LE" => String::from("<="),
        "*AND" | "AND" => String::from("&&"),
        "*OR" | "OR" => String::from("||"),
        "*NOT" | "NOT" => String::from("!"),
        "*CAT" | "CAT" => String::from("+"),
        "*ON" => String::from("true"),
        "*OFF" => String::from("false"),
        _ => {
            if upper.starts_with("*IN")
                && upper.len() > 3
                && upper[3..].chars().all(|c| c.is_ascii_digit())
            {
                return format!("IN{}", &upper[3..]);
            }
            token.to_string()
        }
    }
}

fn contains_logical_operator(expr: &str) -> bool {
    expr.contains("&&") || expr.contains("||") || expr.trim_start().starts_with('!')
}

fn to_java_string_literal(raw: &str) -> String {
    let escaped = raw.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn contains_comparator(expr: &str) -> bool {
    expr.contains("==")
        || expr.contains("!=")
        || expr.contains(">=")
        || expr.contains("<=")
        || expr.contains('>')
        || expr.contains('<')
}

fn build_name_map(program: &IrProgram, class_name: &str) -> BTreeMap<String, String> {
    let mut used = BTreeSet::new();
    used.insert(class_name.to_string());
    used.insert(String::from("main"));
    used.insert(String::from("args"));
    used.insert(String::from("writeRecord"));
    used.insert(String::from("readRecord"));
    used.insert(String::from("truthy"));
    let mut map = BTreeMap::new();
    for symbol in &program.symbols {
        let mut base = sanitize_ident(&symbol.name);
        if base == "main" {
            base = String::from("mainValue");
        }
        let mut candidate = base.clone();
        let mut idx = 1usize;
        while used.contains(&candidate) {
            idx += 1;
            candidate = format!("{base}_{idx}");
        }
        used.insert(candidate.clone());
        map.insert(symbol.name.clone(), candidate.clone());
        map.entry(symbol.name.to_ascii_uppercase())
            .or_insert(candidate);
    }
    map
}

fn build_proc_name_map(
    program: &IrProgram,
    symbol_name_map: &BTreeMap<String, String>,
    class_name: &str,
) -> BTreeMap<String, String> {
    let mut used = BTreeSet::new();
    used.insert(class_name.to_string());
    used.insert(String::from("main"));
    used.insert(String::from("args"));
    used.insert(String::from("writeRecord"));
    used.insert(String::from("readRecord"));
    used.insert(String::from("truthy"));
    for mapped in symbol_name_map.values() {
        used.insert(mapped.clone());
    }

    let mut map = BTreeMap::new();
    for stmt in &program.statements {
        let IrStmt::Call { proc_name } = stmt else {
            continue;
        };

        if map.contains_key(proc_name) {
            continue;
        }

        let base = sanitize_ident(proc_name);
        let mut candidate = base.clone();
        let mut idx = 1usize;
        while used.contains(&candidate) {
            idx += 1;
            candidate = format!("{base}_{idx}");
        }
        used.insert(candidate.clone());
        map.insert(proc_name.clone(), candidate.clone());
        map.entry(proc_name.to_ascii_uppercase())
            .or_insert(candidate);
    }
    map
}

fn map_ident(raw: &str, map: &BTreeMap<String, String>) -> String {
    if let Some(m) = map.get(raw) {
        return m.clone();
    }
    if let Some(m) = map.get(&raw.to_ascii_uppercase()) {
        return m.clone();
    }
    sanitize_ident(raw)
}

fn sanitize_ident(raw: &str) -> String {
    let mut out = String::new();
    for (i, c) in raw.chars().enumerate() {
        let valid = c.is_ascii_alphanumeric() || c == '_';
        if valid {
            if i == 0 && c.is_ascii_digit() {
                out.push('_');
            }
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push_str("value");
    }
    if out.chars().all(|c| c == '_') {
        out.push('v');
    }
    if JAVA_RESERVED_KEYWORDS.contains(&out.as_str()) {
        out.push_str("_v");
    }
    out
}

const JAVA_RESERVED_KEYWORDS: &[&str] = &[
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "record",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "void",
    "volatile",
    "while",
    "_",
    "true",
    "false",
    "null",
    "var",
    "yield",
    "sealed",
    "permits",
    "non-sealed",
];
